# 需要替换$IP和$PORT
# 文件放置于 /etc/nginx/nginx.conf
worker_processes  1;

events {
    worker_connections  10000;
}

stream {
    log_format proxy_logs '$remote_addr [$time_local] '
                          '$protocol $status $bytes_sent $bytes_received '
                          '$session_time';
    access_log /var/log/nginx/stream_access.log proxy_logs;
    error_log  /var/log/nginx/stream_error.log info;

    upstream upstream {
        server $IP:$PORT;
    }

    server {
        listen 80;
        proxy_pass upstream;
    }
}